create table if not exists public.products (
  id bigint primary key,
  name text not null,
  category text not null check (category in ('shoes', 'bags', 'dresses', 'jewelry')),
  price bigint not null check (price >= 0),
  image text not null,
  tag text not null default '',
  position text not null default 'center',
  sizes text not null default '',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'shipped', 'delivered', 'cancelled')),
  total bigint not null check (total >= 0),
  customer_name text not null,
  phone text not null,
  delivery_address text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id),
  product_name text not null,
  unit_price bigint not null check (unit_price >= 0),
  quantity integer not null default 1 check (quantity > 0),
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

alter table public.products add column if not exists sizes text not null default '';
alter table public.products drop constraint if exists products_category_check;
alter table public.products add constraint products_category_check
  check (category in ('shoes', 'bags', 'dresses', 'jewelry'));

create policy "Public can view active products" on public.products
for select to anon, authenticated using (is_active = true);

create policy "Customers can create own orders" on public.orders
for insert to authenticated with check (false);

create policy "Customers can view own orders" on public.orders
for select to authenticated using (auth.uid() = user_id);

create policy "Customers can add items to own orders" on public.order_items
for insert to authenticated with check (false);

create policy "Customers can view own order items" on public.order_items
for select to authenticated using (
  exists (select 1 from public.orders where orders.id = order_items.order_id and orders.user_id = auth.uid())
);

insert into public.products (id, name, category, price, image, tag, position)
values
  (1, 'Ari Slingback', 'shoes', 58000, '/images/shoes.png', 'New', 'center'),
  (2, 'Mila Court Heel', 'shoes', 62000, '/images/shoes.png', 'Bestseller', '60% center'),
  (3, 'Sade Evening Heel', 'shoes', 54000, '/images/shoes.png', '', '38% center'),
  (4, 'Amara Top Handle', 'bags', 94000, '/images/bag.png', 'New', 'center'),
  (5, 'Nora City Bag', 'bags', 88000, '/images/bag.png', '', '55% center'),
  (6, 'Imani Day Tote', 'bags', 105000, '/images/bag.png', 'Limited', '42% center'),
  (7, 'Zuri Satin Midi', 'dresses', 76000, '/images/dress.png', 'New', 'center 15%'),
  (8, 'Ada Occasion Dress', 'dresses', 89000, '/images/dress.png', 'Bestseller', 'center 30%'),
  (9, 'Efe Wrap Dress', 'dresses', 72000, '/images/dress.png', '', 'center 42%')
on conflict (id) do update set
  name = excluded.name, category = excluded.category, price = excluded.price,
  image = excluded.image, tag = excluded.tag, position = excluded.position, is_active = true;

insert into public.products (id, name, category, price, image, tag, position, sizes)
values
  (23, 'Pastel Orchard Jewelry Set', 'jewelry', 25000, '/images/products/pastel-orchard-jewelry-set.jpg', 'New', 'center', ''),
  (24, 'Rainbow Bloom Jewelry Set', 'jewelry', 25000, '/images/products/rainbow-bloom-jewelry-set.jpg', 'New', 'center', ''),
  (25, 'Fuchsia Butterfly Jewelry Set', 'jewelry', 25000, '/images/products/fuchsia-butterfly-jewelry-set.jpg', 'New', 'center', ''),
  (26, 'Crystal Cascade Jewelry Set', 'jewelry', 25000, '/images/products/crystal-cascade-jewelry-set.jpg', 'New', 'center', ''),
  (27, 'Monochrome Ballet Sneaker', 'shoes', 22000, '/images/products/monochrome-ballet-sneaker.jpg', 'New', 'center', 'Black: 37, 38, 41'),
  (28, 'Champagne Blossom Jewelry Set', 'jewelry', 25000, '/images/products/champagne-blossom-jewelry-set.jpg', 'New', 'center', ''),
  (29, 'Pearl Vine Jewelry Set', 'jewelry', 25000, '/images/products/pearl-vine-jewelry-set.jpg', 'New', 'center', ''),
  (30, 'Wine Heritage Slide', 'shoes', 25000, '/images/products/wine-heritage-slide.jpg', 'New', 'center', 'Wine: 37, 41'),
  (31, 'Scarlet Stiletto Mule', 'shoes', 22000, '/images/products/scarlet-stiletto-mule.jpg', 'New', 'center', ''),
  (32, 'Trio Patent Slingback', 'shoes', 25000, '/images/products/trio-patent-slingback.jpg', 'New', 'center', 'Black: 37, 38, 41 · Wine: 37, 41'),
  (33, 'Onyx Rose Stiletto', 'shoes', 22000, '/images/products/onyx-rose-stiletto.jpg', 'New', 'center', 'Black: 37, 38, 41'),
  (34, 'Color Pop Slingback', 'shoes', 25000, '/images/products/color-pop-slingback.jpg', 'New', 'center', 'Black: 37, 38, 41 · Wine: 37, 41 · Green: 42')
on conflict (id) do update set
  name = excluded.name, category = excluded.category, price = excluded.price,
  image = excluded.image, tag = excluded.tag, position = excluded.position,
  sizes = excluded.sizes, is_active = true;

insert into public.products (id, name, category, price, image, tag, position, sizes)
values
  (35, 'Noir H Slide', 'shoes', 22000, '/images/products/noir-h-slide.jpg', 'New', 'center', 'Black: 37, 38, 41'),
  (36, 'Ivory H Slide', 'shoes', 25000, '/images/products/ivory-h-slide.jpg', 'New', 'center', ''),
  (37, 'Wine H Slide', 'shoes', 22000, '/images/products/wine-h-slide.jpg', 'New', 'center', 'Wine: 37, 41'),
  (38, 'Caramel H Slide', 'shoes', 25000, '/images/products/caramel-h-slide.jpg', 'New', 'center', '')
on conflict (id) do update set
  name = excluded.name, category = excluded.category, price = excluded.price,
  image = excluded.image, tag = excluded.tag, position = excluded.position,
  sizes = excluded.sizes, is_active = true;

insert into public.products (id, name, category, price, image, tag, position)
values
  (10, 'Cognac Studded Mini Tote', 'bags', 25000, '/images/products/cognac-studded-mini-tote.jpg', 'New', 'center'),
  (11, 'Amber Beaded Abaya', 'dresses', 37000, '/images/products/amber-beaded-abaya.jpg', 'New', 'center'),
  (12, 'Midnight Beaded Abaya', 'dresses', 40000, '/images/products/midnight-beaded-abaya.jpg', 'New', 'center'),
  (13, 'Azure Embellished Kaftan', 'dresses', 37000, '/images/products/azure-embellished-kaftan.jpg', 'New', 'center'),
  (14, 'Terracotta Tie-Front Gown', 'dresses', 40000, '/images/products/terracotta-tie-front-gown.jpg', 'New', 'center'),
  (15, 'Emerald Stripe Lounge Set', 'dresses', 37000, '/images/products/emerald-stripe-lounge-set.png', 'New', 'center'),
  (16, 'Pearl Tie-Front Gown', 'dresses', 40000, '/images/products/pearl-tie-front-gown.jpg', 'New', 'center'),
  (17, 'Everyday Tote Set', 'bags', 20000, '/images/products/everyday-tote-set.jpg', 'New', 'center'),
  (18, 'Onyx Embroidered Abaya', 'dresses', 37000, '/images/products/onyx-embroidered-abaya.jpg', 'New', 'center'),
  (19, 'Royal Blue Embroidered Abaya', 'dresses', 40000, '/images/products/royal-blue-embroidered-abaya.jpg', 'New', 'center'),
  (20, 'Navy Bloom Lounge Set', 'dresses', 37000, '/images/products/navy-bloom-lounge-set.png', 'New', 'center'),
  (21, 'Classic Shoulder Bag Set', 'bags', 38000, '/images/products/classic-shoulder-bag-set.jpg', 'New', 'center'),
  (22, 'Burnt Orange Structured Bag', 'bags', 40000, '/images/products/burnt-orange-structured-bag.jpg', 'New', 'center')
on conflict (id) do update set
  name = excluded.name, category = excluded.category, price = excluded.price,
  image = excluded.image, tag = excluded.tag, position = excluded.position, is_active = true;

create or replace function public.place_order(
  p_customer_name text,
  p_phone text,
  p_delivery_address text,
  p_items jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_order_id uuid;
  v_total bigint;
  v_expected_items integer;
  v_valid_items integer;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  if nullif(trim(p_customer_name), '') is null
    or nullif(trim(p_phone), '') is null
    or nullif(trim(p_delivery_address), '') is null then
    raise exception 'Complete all delivery details';
  end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Your bag is empty';
  end if;

  with requested as (
    select product_id, quantity
    from jsonb_to_recordset(p_items) as item(product_id bigint, quantity integer)
  )
  select count(*)::integer, count(product.id)::integer,
    coalesce(sum(product.price * requested.quantity), 0)::bigint
  into v_expected_items, v_valid_items, v_total
  from requested
  left join public.products as product
    on product.id = requested.product_id and product.is_active = true
  where requested.quantity > 0;

  if v_expected_items = 0 or v_valid_items <> v_expected_items then
    raise exception 'One or more products are unavailable';
  end if;

  insert into public.orders (user_id, total, customer_name, phone, delivery_address)
  values (v_user_id, v_total, trim(p_customer_name), trim(p_phone), trim(p_delivery_address))
  returning id into v_order_id;

  insert into public.order_items (order_id, product_id, product_name, unit_price, quantity)
  select v_order_id, product.id, product.name, product.price, requested.quantity
  from jsonb_to_recordset(p_items) as requested(product_id bigint, quantity integer)
  join public.products as product
    on product.id = requested.product_id and product.is_active = true
  where requested.quantity > 0;

  return v_order_id;
end;
$$;

revoke all on function public.place_order(text, text, text, jsonb) from public;
grant execute on function public.place_order(text, text, text, jsonb) to authenticated;
